name = "CircularArrays"
uuid = "7a955b69-7140-5f4e-a0ed-f168c5e2e749"
license = "MIT"
desc = "Arrays with fixed size and circular indexing."
authors = ["Vexatos <Stuarzt@gmx.de>"]
url = "https://github.com/Vexatos/CircularArrays.jl"
version = "1.4.0"

[deps]
# The OffsetArrays dependency is not used.
# It's listed as a dependency to allow a compat entry, since versions earlier
# than OffsetArrays 1.3 would cause method ambiguities with this package,
# which are triggered by similar(arr) when arr.data::OffsetArray.
# See #3, #8 and OffsetArrays#6.
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"

[compat]
OffsetArrays = "1.3"
julia = "1.6"
